#!/bin/sh

# This module requires the following boot parameters:
#     aosupdate.device         - specifies device where update artifacts are stored;
#     aosupdate.path           - specifies path whre update artifacts are stored;
#     aosupdate.selinux_module - specifies SELinux module.

# consts

UPDATED_FLAG="updated"
FAIL_FLAG="failed"
DO_UPDATE_FLAG="do_update"
DO_APPLY_FLAG="do_apply"

UPDATE_MOUNT="/mnt/device"
IMAGE_MOUNT="/mnt/image"

UPDATE_IMAGE=""
UPDATE_DIR="${bootparam_aosupdate_disk:+${UPDATE_MOUNT}/}${bootparam_aosupdate_path:-update_rootfs}"
UPDATE_EXT="*.squashfs"

log() {
    local level="$1"
    shift
    echo "<$level>(aos_update) $@" >/dev/kmsg
}

log_error() {
    log 3 "$@"
}

log_info() {
    log 6 "$@"
}

log_debug() {
    log 7 "$@"
}


fail() {
    err="${1:-"unknown error"}"
    log_error "Failed: $err"

    # Put to fail flag file if update mounted
    if [ -z "${bootparam_aosupdate_disk}" ] || grep -qs "$UPDATE_MOUNT" /proc/mounts; then
        mkdir -p "$UPDATE_DIR"
        echo "$err" >"$UPDATE_DIR/$FAIL_FLAG"
    fi
}

error() {
    (
        echo "$@" 1>&2
        log_error "$@"
        exit 1
    )
}

aosupdate_enabled() {
    if [ -z "${bootparam_aosupdate_disk}" ] && [ -z "${bootparam_aosupdate_path}" ]; then
        return 1
    fi

    if [ -n "${bootparam_aosupdate_disk}" ] && [ ! -e "${bootparam_aosupdate_disk}" ]; then
        log_info "Disabled: device ${bootparam_aosupdate_disk} not exist."
        return 1
    fi

    return 0
}

mount_update_disk() {
    log_info "Mount update disk: $bootparam_aosupdate_disk"

    mkdir -p "$UPDATE_MOUNT"
    mount "$bootparam_aosupdate_disk" "$UPDATE_MOUNT"
}

umount_update_disk() {
    if grep -qs "$UPDATE_MOUNT" /proc/mounts && [ ! -f "$UPDATE_DIR/$UPDATED_FLAG" ]; then
        log_info "Umount update disk: $bootparam_aosupdate_disk"

        umount "$UPDATE_MOUNT"
    fi
}

load_selinux_module() {
    if [ -z "${bootparam_aosupdate_selinux_module}" ]; then
        return
    fi

    log_info "Loading selinux module: $bootparam_aosupdate_selinux_module"

    if [ -n "${bootparam_aosupdate_disk}" ]; then
        umount "$UPDATE_MOUNT"
    fi

    mount -t selinuxfs selinuxfs /sys/fs/selinux
    semodule -i "$bootparam_aosupdate_selinux_module"

    if [ -n "${bootparam_aosupdate_disk}" ]; then
        log_info "Remount update disk: $bootparam_aosupdate_disk"

        mount "$bootparam_aosupdate_disk" "$UPDATE_MOUNT" -o context="system_u:object_r:aos_var_run_t:s0"
    fi
}

mount_update_image() {
    log_info "Mount update image: $UPDATE_IMAGE"
    mkdir -p "$IMAGE_MOUNT"
    mount -t squashfs -o loop "$UPDATE_IMAGE" "$IMAGE_MOUNT"
}

umount_update_image() {
    if grep -qs "$IMAGE_MOUNT" /proc/mounts; then
        log_info "Umount update image: $UPDATE_IMAGE"

        umount "$IMAGE_MOUNT"
    fi
}

# Possible actions are: update, apply, revert
get_action() {
    log_debug "Update dir: $UPDATE_DIR"

    if [ -f "$UPDATE_DIR/$DO_APPLY_FLAG" ]; then
        echo "apply"
        return
    fi

    if [ -f "$UPDATE_DIR/$UPDATED_FLAG" ]; then
        echo "revert"
        return
    fi

    if [ -f "$UPDATE_DIR/$DO_UPDATE_FLAG" ]; then
        echo "update"
        return
    fi
}

get_update_type() {
    update=$(cat "$UPDATE_DIR/$DO_UPDATE_FLAG")

    if [ -z "$update" ]; then
        echo "full"
    else
        echo "$update"
    fi
}

do_update() {
    UPDATE_IMAGE="$(find "$UPDATE_DIR" -name "${UPDATE_EXT}" | head -n1)"

    update_type="$(get_update_type)"

    log_info "Start $update_type update..."

    if [ -z "$UPDATE_IMAGE" ]; then
        error "Update image not found"
    fi

    load_selinux_module
    mount_update_image

    case "$update_type" in
    full)
        mount --move "$IMAGE_MOUNT" "$ROOTFS_DIR"
        ;;

    incremental)
        mount -t overlay overlay -o lowerdir="$IMAGE_MOUNT":"$ROOTFS_DIR" "$ROOTFS_DIR"
        ;;

    *)
        error "unknown update type: $update_type"
        ;;
    esac

    touch "$UPDATE_DIR"/"$UPDATED_FLAG"

    log_info  "Successfully updated!"
}

do_revert() {
    log_info "Revert update"

    clear_all_flags

    error "Update not confirmed"
}

cleanup() {
    mount -o remount,ro "$ROOTFS_DIR"
    umount_update_image
}

clear_all_flags() {
    rm -f "$UPDATE_DIR/$DO_UPDATE_FLAG" "$UPDATE_DIR/$UPDATED_FLAG" "$UPDATE_DIR/$DO_APPLY_FLAG" "$UPDATE_DIR/$FAIL_FLAG"
}

do_apply() {
    UPDATE_IMAGE="$(find "$UPDATE_DIR" -name "${UPDATE_EXT}" | head -n1)"

    update_type="$(get_update_type)"

    log_info "Start $update_type apply..."

    load_selinux_module
    mount_update_image
    mount -o remount,rw "$ROOTFS_DIR"

    case "$update_type" in
    full)
        rsync -av -A -X --ignore-times --delete "$IMAGE_MOUNT/" "$ROOTFS_DIR/"
        ;;

    incremental)
        rsync -av -A -X --ignore-times --force "$IMAGE_MOUNT/" "$ROOTFS_DIR/"

        find "$ROOTFS_DIR/" -type c -exec rm -f {} \;
        ;;
    *)
        error "unknown update type: $update_type"
        ;;
    esac

    cleanup
    clear_all_flags

    log_info "Successfully applied!"
}

aosupdate_run() {
    log_info "======================================= Aos update ======================================="

    err=$(
        {
            set -e

    if [ -n "${bootparam_aosupdate_disk}" ]; then
        mount_update_disk
    fi

    case "$(get_action)" in
            update)
                do_update
                ;;

            revert)
                do_revert
                ;;

            apply)
                do_apply
                ;;

            *)
                log_info "Aos update: no action selected"
                ;;
    esac

        } 2>&1 >/dev/null
    )

    if [ $? -ne 0 ]; then
        fail "$err"
        cleanup
    fi

    if [ -n "${bootparam_aosupdate_disk}" ]; then
        umount_update_disk
    fi

    log_info "=========================================================================================="
}
