#!/bin/sh

# This file contains overridden log methods to redirect initramfs messages to /dev/kmsg

# Prints information
msg() {
    echo "<5>initramfs: $*" >/dev/kmsg
}

# Prints error
error() {
    echo "<3>initramfs: $*" >/dev/kmsg
}

# Prints information if verbose bootparam is used
info() {
    [ -n "$bootparam_verbose" ] && echo "<6>initramfs: $*" >/dev/kmsg
}

# Prints information if debug bootparam is used
debug() {
    [ -n "$bootparam_debug" ] && echo "<7>initramfs: $*" >/dev/kmsg
}

# Prints a message and start a endless loop
fatal() {
    echo "<2>initramfs: $1" >/dev/kmsg
    echo "<2>initramfs:" >/dev/kmsg

    if [ -n "$bootparam_init_fatal_sh" ]; then
        sh
    else
        while [ "true" ]; do
            sleep 3600
        done
    fi
}
